# Generated by Django 5.0 on 2023-12-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_question_options'),
        ('Users', '0002_doctor_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='id_Patient',
        ),
        migrations.AddField(
            model_name='responsesquestionnaire',
            name='id_Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.patient'),
        ),
    ]
